package com.alphahotel.model.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * Chambre generated by ValdoR
 */

@Entity
@Table(name="chambre")
@NamedQueries({
        @NamedQuery(name = "Chambre.findByType", query = "SELECT c  FROM Chambre c WHERE c.type = :type_chambre")
})
public class Chambre implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    @Column(name="id")
    private Integer id;

    @Column(name = "libele", nullable = false, length = 30)
    private String libele;

    @Column(name = "descrip", length = 150)
    private String descrip;

    @Column(name = "type", length = 30)
    private String type;

    @Column(name = "photo_url", length = 150)
    private String photo_url;

    @Column(name = "prix_min", length = 11)
    private double prix_min;

    @Column(name = "statut", nullable = false, length = 30)
    private String statut;

    @Column(name = "created_at")
    private Date created_at;

    @Column(name = "updated_at")
    private Date updated_at;

    @ManyToOne(targetEntity = Utilisateur.class, optional = false)
    private Utilisateur utilisateur;

    public Chambre() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLibele() {
        return libele;
    }

    public void setLibele(String libele) {
        this.libele = libele;
    }

    public String getDescrip() {
        return descrip;
    }

    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPhoto_url() {
        return photo_url;
    }

    public void setPhoto_url(String photo_url) {
        this.photo_url = photo_url;
    }

    public double getPrix_min() {
        return prix_min;
    }

    public void setPrix_min(double prix_min) {
        this.prix_min = prix_min;
    }

    public String getStatut() {
        return statut;
    }

    public void setStatut(String statut) {
        this.statut = statut;
    }

    public Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    public Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    public Utilisateur getUtilisateur() {
        return utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
}


